.PHONY: help run build clean schemas

SERVICE_NAME ?= "pennsieve-quick-plot"
# Output for the generated template/tool schemas (regenerated by
# `make schemas`; consumers vendor their own copies from here).
SCHEMAS_DIR ?= schema

.DEFAULT: help

help:
	@echo "Make Help for $(SERVICE_NAME)"
	@echo ""
	@echo "make build   - build the Docker image"
	@echo "make run     - run the processor locally via docker-compose"
	@echo "make clean   - remove output files"
	@echo "make schemas - regenerate the template/tool schemas into $(SCHEMAS_DIR)/"

schemas:
	mkdir -p $(SCHEMAS_DIR)
	python3 -m processor.templates.generate_template_schema --out $(SCHEMAS_DIR)
	python3 -m processor.tools.generate_tools_schema --out $(SCHEMAS_DIR)

build:
	docker build -t $(SERVICE_NAME) .

run:
	docker-compose -f docker-compose.yml down --remove-orphans
	docker-compose -f docker-compose.yml build
	docker-compose -f docker-compose.yml up --exit-code-from processor

clean:
	rm -f data/output/*
	rm -f $(SCHEMAS_DIR)/*.json
