"""
Tests for the generated schemas (templates.json / <family>_tools.json)
that pennsieve-mcp embeds — see generate_template_schema.py and
processor/tools/generate_tools_schema.py.

These pin the *contract* of the generated JSON: entry shape, required-arg
derivation, family join keys, and — most importantly — that every declared
template arg is a real keyword of the template's render() (the check that
keeps ARGS_SPEC from drifting from the code it describes).
"""

from __future__ import annotations

import inspect
import json
from pathlib import Path

from processor import templates
from processor.templates.generate_template_schema import build_schema as build_template_schema
from processor.tools.generate_tools_schema import build_schemas as build_tool_schemas

# The generated snapshots checked into the repo (regenerated by `make schemas`).
_SCHEMA_DIR = Path(__file__).resolve().parents[2] / "schema"


############# templates.json ##################

def test_every_registered_template_is_in_schema():
    names = [t["name"] for t in build_template_schema()["templates"]]
    assert names == templates.known_names()


def test_entry_shape_and_needs_args_derivation():
    by_name = {t["name"]: t for t in build_template_schema()["templates"]}

    edf = by_name["edf_processed_timeseries"]
    assert edf["needs_args"] is True
    assert edf["pipeline_tools"] == "ts_dsp"
    assert edf["extensions"] == [".edf"]
    required = [a["name"] for a in edf["args"] if a["required"]]
    assert required == ["channel", "start_time"]
    assert set(edf["example_args"]) >= set(required)

    csv = by_name["csv_column_distributions"]
    assert csv["needs_args"] is False
    assert csv["pipeline_tools"] is None
    assert csv["extensions"] == [".csv", ".tsv"]
    assert csv["args"] == []


def test_every_template_has_a_summary():
    for t in build_template_schema()["templates"]:
        assert t["summary"].strip(), f"{t['name']} has an empty SUMMARY"


def test_args_spec_matches_render_signature():
    """Every declared arg (and `pipeline`, when a tool family is declared)
    must be an actual keyword parameter of render() — the schema may not
    advertise arguments the code doesn't accept."""
    for entry in build_template_schema()["templates"]:
        mod = templates.get(entry["name"])
        render_params = set(inspect.signature(mod.render).parameters)
        declared = {a["name"] for a in entry["args"]}
        missing = declared - render_params
        assert not missing, (
            f"{entry['name']}: ARGS_SPEC declares {sorted(missing)} "
            f"but render() has no such keyword(s)"
        )
        if entry["pipeline_tools"]:
            assert "pipeline" in render_params, (
                f"{entry['name']} declares PIPELINE_TOOLS but render() "
                f"has no `pipeline` kwarg"
            )


############# <family>_tools.json ##################

def test_tool_schemas_one_file_per_registry():
    schemas = build_tool_schemas()
    assert "ts_tools.json" in schemas
    ts = schemas["ts_tools.json"]
    assert ts["family"] == "ts_dsp"
    names = [t["name"] for t in ts["tools"]]
    assert "highpass_filter" in names and "energy" in names


def test_pipeline_tools_references_resolve():
    """The family join key every template declares must exist among the
    emitted tool schemas (the cross-file invariant the Go side panics on)."""
    families = {c["family"] for c in build_tool_schemas().values()}
    for t in build_template_schema()["templates"]:
        if t["pipeline_tools"] is not None:
            assert t["pipeline_tools"] in families, (
                f"{t['name']} references unknown tool family {t['pipeline_tools']!r}"
            )


############# drift guard: checked-in schema/ vs the code ##################

def test_checked_in_template_schema_matches_code():
    """schema/templates.json must equal a fresh regeneration, so editing a
    template contract without running `make schemas` fails here instead of
    shipping a stale schema for pennsieve-mcp to vendor."""
    on_disk = json.loads((_SCHEMA_DIR / "templates.json").read_text(encoding="utf-8"))
    assert on_disk == build_template_schema(), (
        "schema/templates.json is stale — run `make schemas` and commit the result"
    )


def test_checked_in_tool_schemas_match_code():
    """Same drift guard for every <family>_tools.json (today: ts_tools.json)."""
    for basename, schema in build_tool_schemas().items():
        on_disk = json.loads((_SCHEMA_DIR / basename).read_text(encoding="utf-8"))
        assert on_disk == schema, (
            f"schema/{basename} is stale — run `make schemas` and commit the result"
        )
